title: Ava Francesca Battocchio
# tagline: 
# description: 
#Comment out url when working locally to resolve base urls correctly
url: https://afbat.github.io/

# owner and author info
owner:
  name   : &name "Ava Francesca Battocchio"
  avatar : afbat.jpg
#   bio
  email: battocch@msu.edu
  # socials in author profile
  twitter: _afbat
  github: afbat
  scholar: https://scholar.google.com/citations?user=JuKCgpcAAAAJ&hl

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
#google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here bing_verify: ""

# navigation links
main:
  - title: "About"
    url: /
  - title: "Publications"
    url: /_pages/publications/
  - title: "CV"
    url: /_pages/cv/
  #- title: "CV"
  #  url: /cv/

  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Detroit
future: true
highlighter: rouge
markdown: kramdown
# markdown: redcarpet
# pygments: true
remote_theme: GuangLun2000/GuangLun2000.github.io

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title




plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class

# disqus settings:
# disqus:
#  shortname: 


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]
